[package]
name = "shell"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
drm = "0.14.1"
evdev = "0.13"
gbm = "0.18.0"
kernel.workspace = true
libc = "0.2"
thiserror = "2"

[build-dependencies]
gl_generator = "0.14"
