[package]
name = "shell"
version.workspace = true
edition.workspace = true

[dependencies]
drm = "0.14.1"
kernel.workspace = true
libc = "0.2"
thiserror = "2"

[build-dependencies]
gl_generator = "0.14"
