[workspace]
resolver = "3"
members = ["crates/*", "example"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
abi = { path = "crates/abi" }
kernel = { path = "crates/kernel" }
