[package]
name = "kernel"
version.workspace = true
edition.workspace = true

[dependencies]
lazy_static = { version = "1.5", features = ["spin_no_std"] }
log = "0.4"
spin = "0.10.0"
uart_16550 = "0.4.0"
uefi = { version = "0.36.1", default-features = false }
x86_64 = "0.15.4"
