[package]
name = "emulator"
version.workspace = true
edition.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
abi.workspace = true
anyhow = "1"
eframe = "0.33.3"
egui-phosphor = { version = "0.11", features = ["fill"] }
linux-uapi.workspace = true
