[package]
name = "emulator"
version.workspace = true
edition.workspace = true

[dependencies]
abi.workspace = true
anyhow = "1"
eframe = "0.33.3"
egui-phosphor = { version = "0.11", features = ["fill"] }
kernel.workspace = true
